Накопительная система лояльности «Гофермарт»
sashaaro/go-musthave-diploma-tpl pull request #6
Opened 2024-07-17 18:21 UTC by sashaaro

2024-07-26 18:45 UTC, s-shpak requested changes

2024-07-26 18:45 UTC, s-shpak commented on cmd/gophermart/main.go
> +	cfgMarshal, err := json.MarshalIndent(&cfg, "", "   ")
Все действия с параметрами конфигурации лучше инкапсулировать в отдельной функции (и, возможно, в другом пакете)

2024-07-26 18:45 UTC, s-shpak commented on cmd/gophermart/main.go
> +		logger.Info("CFG: ", string(cfgMarshal))
Объект конфигурации нельзя логировать таким образом, т.к. в нем могут быть пароли, ключи и т.п.

2024-07-26 18:45 UTC, s-shpak commented on pkg/logging/my-logger.go
> +	"github.com/sirupsen/logrus"
Вообще, этим пакетом лучше не пользоваться, он больше не поддерживается. В следующем проекте лучше переходи на `slog` или , например, `zap`.

Этот комментарий можно зарезолвить

2024-07-26 18:45 UTC, s-shpak commented on go.mod
> +go 1.19
Надо перейти на `1.22`

2024-07-26 18:45 UTC, s-shpak commented on go.mod
При вызове `go mod tidy` файлы `go.mod` и `go.sum` меняются. Не забывай их апдейтить периодически или настрой гит хуки для автоматического апдейта

2024-07-26 18:45 UTC, s-shpak commented on internal/app.go
> +	orderComposition "github.com/sashaaro/go-musthave-diploma/internal/composition/order"
В го не принято просто так давать элиасы пакетам, избавься от них

2024-07-26 18:45 UTC, s-shpak commented on internal/app.go
> +	ErrNoSQLConnection = errors.New("нет подключения к БД")
1. Зачем тебе эта ошибка ?
2. Зачем ее экспотировать ?

2024-07-26 18:45 UTC, s-shpak commented on internal/app.go
> +		logger.Error(err)
Если ошибка возвращается, то нет смысла ее логировать, т.к. она будет обработана (например, залогирована) выше

2024-07-26 18:45 UTC, s-shpak commented on internal/app.go
> +		logger.Fatalf("Ошибка создания userComposite %v", err)
Фаталиться в глубине кода нельзя: Fatal приводит к завершению процесса, строчка 41 не выполнится никогда.

Фаталиться можно только в функции `main`. Все другие горутины к этому моменту должны быть завершены

2024-07-26 18:45 UTC, s-shpak commented on internal/app.go
> +	log.Fatal(http.ListenAndServe(*cfg.Port, logging.WithLogging(router, logger)))
`ListenAndServe` всегда возвращает ошибку, даже когда завершается штатно

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/accrual.go
> +type OrdersAPI interface {
В Go интерфейсы определяются в том месте, где используются

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/api/errors.go
> +	//ErrInvalidResponseStatus = errors.New("ответ пришел не с 200 статусом ответа")
deadcode

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/api/orders/send_order.go
> +	res, err := http.DefaultClient.Do(req) // s.HTTPClient.Do(req)
Действительно, стоит поменять на обращение к кастомному клиенту

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/api/orders/send_order.go
> +		s.logger.Errorf("[accrual]: SendOrder Ошибка отправки запроса: %v", err)
Ошибку стоит обернуть и вернуть на строке 52 (посмотри, как оборачивать при помощи `%w`: https://go.dev/blog/go1.13-errors)

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/api/orders/send_order.go
> +	s.logger.Infof("%d %v \n", res.StatusCode, requestURL)
Наверное, стоит делать это на уровне `Debug`

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/client/http.go
> +type httpClient struct {
Было бы хорошо добавить механизм ретраев здесь

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/client/http.go
> +	HashKey *string
Зачем это поле ?

2024-07-26 18:45 UTC, s-shpak commented on internal/client/accrual/http/client/http.go
> +	return &httpClient{
В го есть хорошее правило: возвращать структуры, принмать на вход интерфейсы. Его желательно придерживаться, здесь объясняется почему: https://bryanftan.medium.com/accept-interfaces-return-structs-in-go-d4cab29a301b

2024-07-26 18:45 UTC, s-shpak commented on internal/config/db/migrations/000001_create_gophermart_schema.down.sql
1. Почему бы не слить всем миграции и не обернуть их в транзакцию ?
2. На аттрибуты, используемые для фильтрации, надо повесить индексы

2024-07-26 18:45 UTC, s-shpak commented on internal/db/sql/sql.go
> +func (q SQL) MigrateUp(dataSourceName string) error {
Зачем это экспортировать ? Можно просто вызывать этот метод при создании подключения к БД

2024-07-26 18:45 UTC, s-shpak commented on internal/db/sql/sql.go
> +func (q SQL) MigrateDown(dataSourceName string) error {
В коде это обычно не делается (миграции, как правило, откатываются вручную)

2024-07-26 18:45 UTC, s-shpak commented on internal/repository/order/order.go
> +	_ "github.com/lib/pq"
Зачем этот экспорт ?

2024-07-26 18:45 UTC, s-shpak commented on internal/service/order/order.go
> +	orderResponse, err := u.accrual.SendOrder(ctx, orderDTO)
Правильно ли я понимаю, что сейчас запрос посылается внутри только одной горутины? Если да, то это надо распараллелить. Число одновременных запросов должно быть параметризуемо. `Too many requests` должно все еще останавливать отправление запросов на заданное время

2024-07-26 18:45 UTC, s-shpak commented on internal/http/utils/auth/auth.go
> +	log.Fatalln("нет userID")
Фаталиться нельзя, лучше возвращать ошибку

2024-07-29 17:25 UTC, sashaaro commented on go.mod
> +go 1.19
обновил

2024-07-29 17:25 UTC, sashaaro commented on cmd/gophermart/main.go
> +		logger.Info("CFG: ", string(cfgMarshal))
убрал вообще

2024-07-29 17:25 UTC, sashaaro commented on cmd/gophermart/main.go
> +	cfgMarshal, err := json.MarshalIndent(&cfg, "", "   ")
убрал вообще

2024-07-29 17:25 UTC, sashaaro commented on go.mod
сделал! спс

2024-07-29 17:28 UTC, sashaaro commented on internal/app.go
> +	orderComposition "github.com/sashaaro/go-musthave-diploma/internal/composition/order"
не просто так добавил, тогда тут будут конфикты.

2024-07-29 17:29 UTC, sashaaro commented on internal/app.go
> +	ErrNoSQLConnection = errors.New("нет подключения к БД")
удалил её

2024-07-29 17:30 UTC, sashaaro commented on internal/app.go
> +		logger.Error(err)
поправил

2024-07-29 17:31 UTC, sashaaro commented on internal/app.go
> +		logger.Fatalf("Ошибка создания userComposite %v", err)
убрал, добавил fatal в main

2024-07-29 17:33 UTC, sashaaro commented on internal/app.go
> +	log.Fatal(http.ListenAndServe(*cfg.Port, logging.WithLogging(router, logger)))
взял примеры из документации https://pkg.go.dev/net/http
ну а как тогда сделать? вообще не обрабатывать ошибку нельзя

2024-07-29 17:35 UTC, sashaaro commented on internal/client/accrual/http/api/errors.go
> +	//ErrInvalidResponseStatus = errors.New("ответ пришел не с 200 статусом ответа")
убрал

2024-07-29 17:37 UTC, sashaaro commented on internal/client/accrual/http/api/orders/send_order.go
> +	res, err := http.DefaultClient.Do(req) // s.HTTPClient.Do(req)
добавил

2024-07-29 17:40 UTC, sashaaro commented on internal/client/accrual/http/api/orders/send_order.go
> +		s.logger.Errorf("[accrual]: SendOrder Ошибка отправки запроса: %v", err)
добавил

2024-07-29 17:42 UTC, sashaaro commented on internal/client/accrual/http/api/orders/send_order.go
> +	s.logger.Infof("%d %v \n", res.StatusCode, requestURL)
исправил

2024-07-29 17:44 UTC, sashaaro commented on internal/client/accrual/http/client/http.go
> +	HashKey *string
убрал

2024-08-01 15:38 UTC, sashaaro commented on go.mod
> +go 1.19
https://github.com/sashaaro/go-musthave-diploma/actions/runs/10149182545/job/28063536437?pr=6
падает джоба

2024-08-01 15:41 UTC, sashaaro commented on internal/db/sql/sql.go
> +func (q SQL) MigrateUp(dataSourceName string) error {
поправил

2024-08-01 15:42 UTC, sashaaro commented on internal/db/sql/sql.go
> +func (q SQL) MigrateDown(dataSourceName string) error {
вообще убрал

2024-08-01 15:58 UTC, sashaaro commented on internal/repository/order/order.go
> +	_ "github.com/lib/pq"
убрал

2024-08-01 16:00 UTC, sashaaro commented on internal/http/utils/auth/auth.go
> +	log.Fatalln("нет userID")
убрал вообще, по логике всегда будет пользователь

2024-08-01 16:02 UTC, sashaaro commented on internal/client/accrual/accrual.go
> +type OrdersAPI interface {
я не успел пока ознакомится с этой концепцией. предлагаю пока оставить так.

2024-08-01 16:06 UTC, sashaaro commented on internal/client/accrual/http/client/http.go
> +type httpClient struct {
в условиях не было такого, предлагаю оставить так, т.к. не успеваю

2024-08-01 16:07 UTC, sashaaro commented on internal/client/accrual/http/client/http.go
> +	return &httpClient{
спасибо поправил

2024-08-01 16:12 UTC, sashaaro commented on internal/config/db/migrations/000001_create_gophermart_schema.down.sql
разрабатывал поэтапно, поэтому всё в разных файлах\
объединил

2024-08-01 16:16 UTC, sashaaro commented on internal/config/db/migrations/000001_create_gophermart_schema.down.sql
добавил индексы для логина и для order number

2024-08-01 16:17 UTC, sashaaro commented on pkg/logging/my-logger.go
> +	"github.com/sirupsen/logrus"
хорошо, принял к сведению

2024-08-01 16:20 UTC, sashaaro commented on internal/service/order/order.go
> +	orderResponse, err := u.accrual.SendOrder(ctx, orderDTO)
нет, каждый заказ обрабатываются в собственной го рутине

2024-08-01 22:38 UTC, s-shpak approved these changes

2024-08-02 08:10 UTC, merged